#!/bin/sh
ABI=4.4.3
JOBS=6

TOOLCHAIN="arm-eabi-4.6-Linaro"
CROSS_COMPILE_PREFIX=arm-eabi-

PATH="/home/nonamer/$TOOLCHAIN/bin:$PATH"

time make -j$JOBS ARCH=arm CROSS_COMPILE=$CROSS_COMPILE_PREFIX EXTRA_AFLAGS="-mfpu=neon"
